name: keymap
description: A reusable keyboard shortcuts widget with a flexible, minimal UI and focus handling.
version: 0.0.5
homepage: https://github.com/pmutisya/keymap

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
